version: '3'
services:
  ubuntu-androidbuild:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./workspace:/mnt/workspace
      - ./tmp:/tmp
    network_mode: "bridge"
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    tmpfs:
      - /run
      - /run/lock
    hostname: ubuntu-androidbuild
    cap_add:
      - ALL
