version: '3'
services:
  ubuntu-androidbuild:
    container_name: ubuntu-androidbuild
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./workspace:/workspace
    network_mode: "bridge"
    privileged: true
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    hostname: ubuntu-androidbuild
