version: '3'
services:
  docker-ubuntu-systemd:
    container_name: docker-ubuntu-systemd
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./workspace:/workspace
    network_mode: "bridge"
    privileged: true
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    hostname: docker-ubuntu-systemd
